### ISSUE TITLE
Zulip hanging with white screen

### ISSUE THREAD

**Issue by Alizter** [zulip/zulip-desktop#1235]
Hi, I've installed Zulip with nix using
```sh
$ nix profile install nixpkgs#zulip
```

But I cannot start Zulip at all. When I try to I get the following in the terminal and Zulip opens a blank window:

<details>
<summary> $ zulip --verbose </summary>

```sh
$ zulip --verbose
Gtk-Message: 19:06:49.753: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:06:49.759: Failed to load module "canberra-gtk-module"
[412106:0906/190649.951408:ERROR:angle_platform_impl.cc(44)] Display.cpp:966 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[412106:0906/190649.951840:ERROR:gl_surface_egl.cc(808)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[412106:0906/190649.952050:ERROR:gl_surface_egl.cc(1430)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[412106:0906/190649.953735:ERROR:angle_platform_impl.cc(44)] Display.cpp:966 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[412106:0906/190649.954016:ERROR:gl_surface_egl.cc(808)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[412106:0906/190649.954211:ERROR:gl_surface_egl.cc(1430)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[412106:0906/190649.954388:ERROR:gl_ozone_egl.cc(20)] GLSurfaceEGL::InitializeOneOff failed.
[412106:0906/190649.968393:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
Reverting GDK_BACKEND to work around https://github.com/electron/electron/issues/28436
[412061:0906/190650.266721:ERROR:platform_font_skia.cc(246)] Could not find any font: Ubuntu, sans. Falling back to the default
[412131:0906/190650.741961:ERROR:angle_platform_impl.cc(44)] Display.cpp:966 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[412131:0906/190650.742860:ERROR:gl_surface_egl.cc(808)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[412131:0906/190650.747027:ERROR:gl_surface_egl.cc(1430)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[412131:0906/190650.749437:ERROR:angle_platform_impl.cc(44)] Display.cpp:966 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[412131:0906/190650.749704:ERROR:gl_surface_egl.cc(808)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[412131:0906/190650.750008:ERROR:gl_surface_egl.cc(1430)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[412131:0906/190650.752188:ERROR:gl_ozone_egl.cc(20)] GLSurfaceEGL::InitializeOneOff failed.
[412131:0906/190650.785366:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[412144:0906/190650.902298:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
MESA-LOADER: failed to open iris: /run/opengl-driver/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri, suffix _dri)
failed to load driver: iris
MESA-LOADER: failed to open zink: /run/opengl-driver/lib/dri/zink_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri, suffix _dri)
failed to load driver: zink
MESA-LOADER: failed to open kms_swrast: /run/opengl-driver/lib/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri, suffix _dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /run/opengl-driver/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri, suffix _dri)
failed to load swrast driver
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: ERR_FAILED (-2) loading 'file:///nix/store/66rqq441phr18scyfbrbl83r58c8w31w-zulip-5.9.3-extracted/resources/app.asar/app/renderer/main.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:161:8022)
    at EventEmitter.emit (node:events:402:35)
    at EventEmitter.emit (node:domain:475:12)
    at EventEmitter.emitter.emit (/nix/store/66rqq441phr18scyfbrbl83r58c8w31w-zulip-5.9.3-extracted/resources/app.asar/node_modules/@sentry/electron/main/integrations/electron-breadcrumbs.js:121:20)
(node:412061) UnhandledPromiseRejectionWarning: Error: ERR_FAILED (-2) loading 'file:///nix/store/66rqq441phr18scyfbrbl83r58c8w31w-zulip-5.9.3-extracted/resources/app.asar/app/renderer/main.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:161:8022)
    at EventEmitter.emit (node:events:402:35)
    at EventEmitter.emit (node:domain:475:12)
    at EventEmitter.emitter.emit (/nix/store/66rqq441phr18scyfbrbl83r58c8w31w-zulip-5.9.3-extracted/resources/app.asar/node_modules/@sentry/electron/main/integrations/electron-breadcrumbs.js:121:20)
(Use `zulip --trace-warnings ...` to show where the warning was created)
(node:412061) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at send (/nix/store/66rqq441phr18scyfbrbl83r58c8w31w-zulip-5.9.3-extracted/resources/app.asar/app/main/typed-ipc-main.js:7:14)
    at Timeout._onTimeout (/nix/store/66rqq441phr18scyfbrbl83r58c8w31w-zulip-5.9.3-extracted/resources/app.asar/app/main/index.js:304:39)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
[412061:0906/190705.389407:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[412061:0906/190705.392544:ERROR:object_proxy.cc(623)] Failed to call method: org.gnome.ScreenSaver.GetActive: object_path= /: org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/”
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at send (/nix/store/66rqq441phr18scyfbrbl83r58c8w31w-zulip-5.9.3-extracted/resources/app.asar/app/main/typed-ipc-main.js:7:14)
    at BrowserWindow.<anonymous> (/nix/store/66rqq441phr18scyfbrbl83r58c8w31w-zulip-5.9.3-extracted/resources/app.asar/app/main/index.js:92:35)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.emitter.emit (/nix/store/66rqq441phr18scyfbrbl83r58c8w31w-zulip-5.9.3-extracted/resources/app.asar/node_modules/@sentry/electron/main/integrations/electron-breadcrumbs.js:121:20)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at send (/nix/store/66rqq441phr18scyfbrbl83r58c8w31w-zulip-5.9.3-extracted/resources/app.asar/app/main/typed-ipc-main.js:7:14)
    at BrowserWindow.<anonymous> (/nix/store/66rqq441phr18scyfbrbl83r58c8w31w-zulip-5.9.3-extracted/resources/app.asar/app/main/index.js:92:35)
    at BrowserWindow.emit (node:events:402:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.emitter.emit (/nix/store/66rqq441phr18scyfbrbl83r58c8w31w-zulip-5.9.3-extracted/resources/app.asar/node_modules/@sentry/electron/main/integrations/electron-breadcrumbs.js:121:20)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at send (/nix/store/66rqq441phr18scyfbrbl83r58c8w31w-zulip-5.9.3-extracted/resources/app.asar/app/main/typed-ipc-main.js:7:14)
    at Timeout._onTimeout (/nix/store/66rqq441phr18scyfbrbl83r58c8w31w-zulip-5.9.3-extracted/resources/app.asar/app/main/index.js:304:39)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

</details>

Nix reports the Zulip version as 5.9.3.

**Comment by erikdstock** [comment]
I'm not sure this is the same issue, but i have a white screen as well - installed on macOS via download from the website.

**Comment by nbuckley** [comment]
Similar, I have a white screen periodically as well. Win 10 desktop app. App is not hanging though -- seems to be running fine technically. I can right click and a small Copy / Paste right click menu shows. The entire app basically is just white, other than the thin sidebar to select one's organization.

Zulip 5.11.1
