### ISSUE TITLE
Windows app not working - stuck on loading

### ISSUE THREAD

**Issue by ADMarian** [zulip/zulip-desktop#373]
Freshly installed the app and it's stuck. It's looping on refresh and it doesn't allow me to do anything. I tried looking for the logs in order to provide possible in-depth details, but I can't find those either.

![zulip](https://user-images.githubusercontent.com/34919672/34613785-ba2e9f82-f237-11e7-8dab-6f22239a17a8.png)

Zulip 1.7.0
Electron 1.6.15
win32 x64 10.0.15063

**Comment by akashnimare** [comment]
@ADMarian hey, can you paste the console logs of app? You can find it in  `Menu > View Toggle DevTools for Active Tab` and then `developer tools > console tab`.

![image](https://user-images.githubusercontent.com/2263909/32502882-e3e8189e-c401-11e7-9ac2-de57e1755bd2.png)

**Comment by ADMarian** [comment]
Hi @akashnimare - couldn't open the ``` DevTools for Active Tab ```. Instead, I'll paste the error from the ``` DevTools for Zulip App ```

```
inner: SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at JsonDB.load (C:\Program Files\Zulip\resources\app.asar\node_modules\node-json-db\JsonDB.js:215:30)
    at JsonDB._getData (C:\Program Files\Zulip\resources\app.asar\node_modules\node-json-db\JsonDB.js:75:14)
    at JsonDB.getData (C:\Program Files\Zulip\resources\app.asar\node_modules\node-json-db\JsonDB.js:70:21)
    at ConfigUtil.getConfigItem (C:\Program Files\Zulip\resources\app.asar\renderer\js\utils\config-util.js:30:25)
    at Object.<anonymous> (C:\Program Files\Zulip\resources\app.asar\renderer\js\tray.js:220:16)
    at Object.<anonymous> (C:\Program Files\Zulip\resources\app.asar\renderer\js\tray.js:224:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

message: "Unexpected token  in JSON at position 0"

stack: "SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at JsonDB.load (C:\Program Files\Zulip\resources\app.asar\node_modules\node-json-db\JsonDB.js:215:30)
    at JsonDB._getData (C:\Program Files\Zulip\resources\app.asar\node_modules\node-json-db\JsonDB.js:75:14)
    at JsonDB.getData (C:\Program Files\Zulip\resources\app.asar\node_modules\node-json-db\JsonDB.js:70:21)
    at ConfigUtil.getConfigItem (C:\Program Files\Zulip\resources\app.asar\renderer\js\utils\config-util.js:30:25)
    at Object.<anonymous> (C:\Program Files\Zulip\resources\app.asar\renderer\js\tray.js:220:16)
    at Object.<anonymous> (C:\Program Files\Zulip\resources\app.asar\renderer\js\tray.js:224:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)"

message: "Can't Load Database"
name: "DatabaseError"
stack: "NestedError: Can't Load Database
    at DatabaseError.NestedError (C:\Program Files\Zulip\resources\app.asar\node_modules\node-json-db\lib\Errors.js:7:25)
    at new DatabaseError (C:\Program Files\Zulip\resources\app.asar\node_modules\node-json-db\lib\Errors.js:29:33)
    at JsonDB.load (C:\Program Files\Zulip\resources\app.asar\node_modules\node-json-db\JsonDB.js:218:25)
    at JsonDB._getData (C:\Program Files\Zulip\resources\app.asar\node_modules\node-json-db\JsonDB.js:75:14)
    at JsonDB.getData (C:\Program Files\Zulip\resources\app.asar\node_modules\node-json-db\JsonDB.js:70:21)
    at ConfigUtil.getConfigItem (C:\Program Files\Zulip\resources\app.asar\renderer\js\utils\config-util.js:30:25)
    at Object.<anonymous> (C:\Program Files\Zulip\resources\app.asar\renderer\js\tray.js:220:16)
    at Object.<anonymous> (C:\Program Files\Zulip\resources\app.asar\renderer\js\tray.js:224:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)"
```

![zulip_error](https://user-images.githubusercontent.com/34919672/34614507-60d1310e-f23a-11e7-9dcb-74d8edbaf44d.png)

**Comment by akashnimare** [comment]
@ADMarian cool, this is a familiar error. We have recently fixed this bug in master and it'll be pushed in next version. To fix this, please remove `C:\Users\[name]\AppData\Roaming\Zulip\` directory and start the app again. Let me know if it works.

**Comment by ADMarian** [comment]
@akashnimare - that did the trick, thanks!

**Comment by akashnimare** [comment]
@ADMarian can you please tell me how you ended up seeing the looping page (steps you followed)? Have you done anything else apart from starting the app? I'm guessing this is the first time you run the app and have not added any Zulip org before.

**Comment by ADMarian** [comment]
@akashnimare - I have previously installed the app and added an organization. Randomly it stopped working one day. Then I reinstalled the app and the issue kept showing.

When I used the app, I didn't do anything out of the common. Just chatting and adjusted a few preferences like notifications and sounds.

I guess I should have mentioned that earlier. Sorry, my bad!

**Comment by akashnimare** [comment]
No worries 👍
